name: publish distributions
on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master

jobs:
  build-and-publish:
    name: Build and publish Python distro to (Test)PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pep517
      run: |
        python -m pip install pep517 --user
    - name: Build a binary wheel and a source tarball
      env:
        IS_COMMIT_TAGGED: >-
          ${{ startsWith(github.ref, 'refs/tags') }}
      run: |
        echo "build python package for distribution"
    - name: Publish distribution 📦 to Test PyPI
      # every PR will trigger a push event on master, so check the push event is actually coming from master
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'kratsg/github-action-test'
      run: |
        echo "publish to testpypi"
    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.repository == 'kratsg/github-action-test'
      run: |
        echo "publish to pypi"
